### ISSUE TITLE
Correction for variable scope

### ISSUE THREAD

**Issue by mohammedyh** [yusufcodes/beginnerjavascript#4]

**Comment by yusufcodes** [comment]
Hi there! Thanks for reading my notes😊. Below is a quick copy of what is on my notes:

_'let' is block scoped, whereas 'var' is function scoped, meaning that you can refer to any var variable anywhere within a function and it will be available._

It appears that I've correctly described let and var, however if I have written it incorrectly anywhere else please point me to where this is! Thank you🙂

**Comment by yusufcodes** [comment]
Hi there, thanks for reading my notes😊

It appears I have written this in the following paragraph:

_'let' is block scoped, whereas 'var' is function scoped, meaning that you can refer to any var variable anywhere within a function and it will be available._

If I have written it incorrectly somewhere else though please show me. Thanks in advance!
